version: '3.8'

services:
  # MongoDB service
  mongodb:
    image: mongo:latest
    container_name: sql-learning-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=sql-learning-platform
    networks:
      - sql-learning-network

  # Backend service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev  # Dockerfile for development
    container_name: sql-learning-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGODB_URI=mongodb://mongodb:27017/sql-learning-platform
      - JWT_SECRET=your_jwt_secret_here
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CORS_ORIGIN=http://localhost:5173
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - sql-learning-network

  # Frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev  # Dockerfile for development
    container_name: sql-learning-frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:5000/api
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - sql-learning-network

networks:
  sql-learning-network:
    driver: bridge

volumes:
  mongodb_data: 